/*INSERE DADOS NA TABELA DE VEICULO*/
INSERT INTO LABDATABASE.VEICULO VALUES(VEICULO_CODCARRO_VEICULO_SEQ.NEXTVAL, 'Q8');
INSERT INTO LABDATABASE.VEICULO VALUES(VEICULO_CODCARRO_VEICULO_SEQ.NEXTVAL, 'C3');
INSERT INTO LABDATABASE.VEICULO VALUES(VEICULO_CODCARRO_VEICULO_SEQ.NEXTVAL, 'CORSA');
INSERT INTO LABDATABASE.VEICULO VALUES(VEICULO_CODCARRO_VEICULO_SEQ.NEXTVAL, 'ONYX');
INSERT INTO LABDATABASE.VEICULO VALUES(VEICULO_CODCARRO_VEICULO_SEQ.NEXTVAL, 'DS4');
INSERT INTO LABDATABASE.VEICULO VALUES(VEICULO_CODCARRO_VEICULO_SEQ.NEXTVAL, 'CELTA');
INSERT INTO LABDATABASE.VEICULO VALUES(VEICULO_CODCARRO_VEICULO_SEQ.NEXTVAL, 'COROLA');
INSERT INTO LABDATABASE.VEICULO VALUES(VEICULO_CODCARRO_VEICULO_SEQ.NEXTVAL, 'COBALT');
INSERT INTO LABDATABASE.VEICULO VALUES(VEICULO_CODCARRO_VEICULO_SEQ.NEXTVAL, 'ASTRA');
INSERT INTO LABDATABASE.VEICULO VALUES(VEICULO_CODCARRO_VEICULO_SEQ.NEXTVAL, 'FIAT TORO');
INSERT INTO LABDATABASE.VEICULO VALUES(VEICULO_CODCARRO_VEICULO_SEQ.NEXTVAL, 'SANDEIRO STEPAWAY');
INSERT INTO LABDATABASE.VEICULO VALUES(VEICULO_CODCARRO_VEICULO_SEQ.NEXTVAL, 'POLO');

/*INSERE DADOS NA TABELA DE CLIENTES*/
INSERT INTO LABDATABASE.CLIENTE VALUES('01234567891', 'JOÃO GABRIEL');
INSERT INTO LABDATABASE.CLIENTE VALUES('20123456789', 'JOÃO GUILHERME');
INSERT INTO LABDATABASE.CLIENTE VALUES('32012345678', 'JOÃO JOSÉ');
INSERT INTO LABDATABASE.CLIENTE VALUES('43201234567', 'JOSÉ ANTÔNIO');
INSERT INTO LABDATABASE.CLIENTE VALUES('54320123456', 'JOSÉ CARLOS');
INSERT INTO LABDATABASE.CLIENTE VALUES('65432012345', 'ANTÔNIO CARLOS');
INSERT INTO LABDATABASE.CLIENTE VALUES('76543201234', 'CARLOS ANTÔNIO');
INSERT INTO LABDATABASE.CLIENTE VALUES('87654320123', 'MARCO ANTÔNIO');

/*INSERE DADOS NA TABELA DE FORNECEDORES*/
INSERT INTO LABDATABASE.VENDAVEICULO VALUES('01234567891234', '90000');
INSERT INTO LABDATABASE.VENDAVEICULO VALUES('00123456789123', '270000');
INSERT INTO LABDATABASE.VENDAVEICULO VALUES('00012345678912', '120000');
INSERT INTO LABDATABASE.VENDAVEICULO VALUES('00001234567891', '399999');

COMMIT;